### ISSUE TITLE
Sound effects. 200 pts

### ISSUE THREAD

**Issue by nikolasjchaconas** [UCSB-CS56-Projects/cs56-games-tetris#18]
Add sound effects that sound when blocks are dropped, a row is cleared, and for game over.

**Comment by dcoffill** [comment]
Approved
Estimated ~200

**Comment by Tektonbuilds** [comment]
F16 OK 200 pts

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-tetris/pull/42
