### ISSUE TITLE
Add/Improve on Javadoc Comments. 50 pts

### ISSUE THREAD

**Issue by davzaman** [UCSB-CS56-Projects/cs56-games-tetris#20]
Much of the source code is either missing javadoc comments or has poorly written javadoc comments.

**Comment by hannavigil** [comment]
Estimated 50 points

**Comment by Tektonbuilds** [comment]
F16 OK 50 pts

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-tetris/pull/42
