### ISSUE TITLE
Game Sometimes Doesn't Wait to Spawn New Block. 100 pts

### ISSUE THREAD

**Issue by FourPieces** [UCSB-CS56-Projects/cs56-games-tetris#27]
There is a bug where every once in a while, the game will not wait to spawn the next block, thus spawning two blocks and triggering an instant game over.

**Comment by FourPieces** [comment]
Estimated 100pts

**Comment by hannavigil** [comment]
W16 OK

**Comment by Tektonbuilds** [comment]
F16 OK 100 pts

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-tetris/pull/34
