### ISSUE TITLE
Game Doesn't Wait to Clear Rows. 50 pts

### ISSUE THREAD

**Issue by FourPieces** [UCSB-CS56-Projects/cs56-games-tetris#28]
When a block is falling, it will automatically clear complete rows as it falls instead of waiting until the end of the fall to clear completed rows. This causes rows that shouldn't be cleared to be cleared, which doesn't really break anything but is definitely a bug with how the game should operate.

For example: if the L block is hard dropped, the row will be cleared before the L can be animated to show that it dropped.

**Comment by FourPieces** [comment]
Estimated 50pts

**Comment by hannavigil** [comment]
W16 OK

**Comment by Tektonbuilds** [comment]
F16 OK 50 pts

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-tetris/pull/34
