### ISSUE TITLE
Add a "floor" to the bottom of tetris board. 50 pts

### ISSUE THREAD

**Issue by davzaman** [UCSB-CS56-Projects/cs56-games-tetris#29]
add a "floor" to the tetris board at the bottom so players can visualize where blocks will land

**Comment by FourPieces** [comment]
Estimated 100pts

**Comment by hannavigil** [comment]
W16 OK

**Comment by Tektonbuilds** [comment]
They probably mean a grid.

**Comment by Tektonbuilds** [comment]
Additional 200 points for animating the blocks such that the blocks will move one unit at a time like in the actual Tetris games.

**Comment by Tektonbuilds** [comment]
This won't take long, estimated 50 points.

**Comment by Tektonbuilds** [comment]
F16 OK 50 pts

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-tetris/pull/42
