### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by andrewberls** [UCSB-CS56-Projects/cs56-games-tetris#3]
This depends on https://github.com/UCSB-CS56-Projects/cs56-games-tetris/issues/2. Once the game is interactive and playable, it would be nice to have a full GUI with interesting graphics, menus to start/restart gameplay, and optionally accompanying sound effects.

~estimated 400

**Comment by FourPieces** [comment]
What about the GUI specifically still needs work, since we have separate issues regarding individual aspects of the GUI? It seems like the GUI has been implemented mostly but this issue remains open.
