### ISSUE TITLE
Add a grid to game for visualization. 300 pts

### ISSUE THREAD

**Issue by Tektonbuilds** [UCSB-CS56-Projects/cs56-games-tetris#33]
Tetris has a grid to guide players when they are placing blocks. This will take a while to accomplish.
Estimated: 100-200 pts.
In addition, fixing the animation such that the block move a unit at a time will match the game's style much better.
Estimated: 100 pts.

Estimated total: 300 pts

**Comment by Tektonbuilds** [comment]
F16 OK 300 pts

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-tetris/pull/42
