### ISSUE TITLE
Pause should not reset the timer. 100pts

### ISSUE THREAD

**Issue by wpeery** [ucsb-cs56-projects/cs56-games-tetris#43]
By alternating pause/unpause you can stop a block in its tracks. This shouldnt happen.
Estimated 100pts.

**Comment by JohnUCSB** [comment]
There is a timer for when the blocks move down one square in the grid. When pause is pressed the time resets. But the timer should be kept that its before-pause time instead of resettting.
F16 OK (100 pts)

**Comment by john-lau** [comment]
Issue seems to be fixed
