### ISSUE TITLE
Create helper method for actionPerformed. 50pts

### ISSUE THREAD

**Issue by wpeery** [UCSB-CS56-Projects/cs56-games-tetris#47]
Create a helper function to use in place of the case statement in the actionPerformed of TetrisBoard.
Estimated 50pts.

**Comment by JohnUCSB** [comment]
F16 OK (50 pts)

**Comment by jesmarsc** [comment]
As a solution, a helper class was made AND refactored rather than simply making a helper function. Less code inside of TetrisBoard.java.
Estimated 100pts for different solution.

**Comment by KevinLee00** [comment]
Approved 100 pts.
