### ISSUE TITLE
Proposed Issue - Fix first block color

### ISSUE THREAD

**Issue by sumersinha** [UCSB-CS56-Projects/cs56-games-tetris#5]
The first block keeps changing colors as the new blocks are added to the game. This only happens with the first block. Fix this bug.
A rotate function should be added to add more functionality to the game, make it more Tetris-like.

**Comment by hannavigil** [comment]
These issues should be two separate issues.  For the rotate block issue see #25
This will change  point value for this issue to:
~50 points
